### POST request with json body to workers
POST http://localhost:8085/hr/workers
Content-Type: application/json
{
  "positionId": 1,
  "name": "Andrey",
  "patronymic": "Andreev",
  "email": "Andrey@gmail.com",
  "phone": "12345",
  "salary": 123.4,
  "isWorking": true
}

### POST request with json body to positions
POST http://localhost:8085/hr/positions
Content-Type: application/json
{
    "position" : "Директор"
}

### POST request with json body to shedules
POST http://localhost:8085/hr/shedules
Content-Type: application/json
{
    "id" : 7,
    "hoursPerWeek" : 5.5,
    "vacationDays" : 6,
    "vacationSchedule" : 7
}